"""Typed protocols for ARGUS MCP capabilities."""

from typing import Protocol

from argus.mcp.schemas import (
    CompanyEvent,
    CompanyProfile,
    MarketQuote,
    NewsArticle,
    RegulationNotice,
    SupplierRecord,
    TradeControl,
)


class NewsClient(Protocol):
    def search_news(self, query: str, date_range: str | None = None, region: str | None = None) -> list[NewsArticle]: ...
    def get_article(self, article_id: str) -> NewsArticle: ...
    def search_company_news(self, company: str) -> list[NewsArticle]: ...


class GovernmentClient(Protocol):
    def search_regulation(self, query: str, jurisdiction: str | None = None) -> list[RegulationNotice]: ...
    def get_notice(self, document_id: str) -> RegulationNotice: ...
    def search_trade_controls(self, product: str, country: str) -> list[TradeControl]: ...


class MarketClient(Protocol):
    def get_stock_price(self, symbol: str) -> MarketQuote: ...
    def get_fx_rate(self, pair: str) -> MarketQuote: ...
    def get_commodity_price(self, symbol: str) -> MarketQuote: ...
    def get_market_news(self, symbol: str) -> list[NewsArticle]: ...


class CompanyClient(Protocol):
    def company_profile(self, company: str) -> CompanyProfile: ...
    def supplier_lookup(self, company: str) -> SupplierRecord: ...
    def get_company_events(self, company: str) -> list[CompanyEvent]: ...

